#! /bin/sh
### BEGIN INIT INFO
# Provides: tomcat
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Wemo devices simulator
# Description: This file starts and stops Wemo devices simulator
# 
### END INIT INFO

ECHO_DIR=/home/pi/echo

case "$1" in
 start)
   su pi -c python $ECHO_DIR/echo-mqtt.py 
   ;;
 stop)
   #su joe -c $TOMCAT_DIR/bin/shutdown.sh
   sleep 10
   ;;
 restart)
   #su joe -c $TOMCAT_DIR/bin/shutdown.sh
   sleep 20
   su pi -c python $ECHO_DIR/echo-mqtt.py 
   ;;
 *)
   echo "Usage: wemo {start|stop|restart}" >&2
   exit 3
   ;;
esac